# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM {{ cookiecutter.docker_baseimage }}

LABEL maintainer='{{ cookiecutter.author_name }}'
# {{ cookiecutter.description.replace('\'', '') }}

RUN apt-get update && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set LANG environment
ENV LANG C.UTF-8

# Set the working directory
WORKDIR /app

# Script to run pylint
COPY {{ cookiecutter.repo_name }}/tests/run_pylint.sh /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install pylint and python packages listed in test-requirements.txt
RUN pip --no-cache-dir install -r /app/requirements.txt && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

