#!/usr/bin/groovy

@Library(['github.com/indigo-dc/jenkins-pipeline-library']) _

pipeline {
    environment {
        job_location = "Pipeline-as-code/DEEP-OC-org/DEEP-OC-{{ cookiecutter.repo_name }}"
    }
    stages {
        stage('Fetch the repository') {
            steps {
                checkout scm
            }
        }
	
        stage('Style analysis: PEP8') {
            steps {
                ToxEnvRun('pep8')
            }
            post {
                always {
                    WarningsReport('Pep8')
                }
            }
        }

        stage('Style analysis: Pylint') {
            steps {
                ToxEnvRun('pylint')
            }
            post {
                always {
                    WarningsReport('Pylint')
                }
            }
        }

        stage("Re-build DEEP-OC-{{ cookiecutter.repo_name }} Docker image") {
            steps {
                JenkinsBuildJob("${env.job_location}")
            }
        }
    }
}
