#!/usr/bin/groovy

@Library(['github.com/indigo-dc/jenkins-pipeline-library']) _

pipeline {
    agent {
        label 'docker-build'
    }

    environment {
        dockerhub_repo = "deephdc/test-DEEP-OC-{{ cookiecutter.repo_name }}"
    }

    stages {
        stage('DockerHub delivery') {
            steps{
                checkout scm
                script {
                    image_id = DockerBuild("${env.dockerhub_repo}, env.BRANCH_NAME)
                }
            }
            post {
                success {
                    DockerPush(image_id)
                }
                failure {
                    DockerClean()
                }
                always {
                    cleanWs()
                }
            }
        }
    }
}
